### ISSUE TITLE
errors when trying to build

### ISSUE THREAD

**Issue by 0i0** [tmcw/node-corelocation#3]
i'm new to this native stuff, can you help a bit?

> $ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.6.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node_corelocation/core.o
../core.mm:78:20: warning: incompatible pointer types sending 'LLHolder *' to parameter of type 'id<NSFileManagerDelegate> _Nullable' [-Wincompatible-pointer-types]
        [g_lm setDelegate:obj];
                          ^~~
../core.mm:95:33: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> GetLocation(const Arguments& args) {
                                ^~~~~~~~~
                                v8::internal::Arguments
/Users/leo/.node-gyp/8.6.0/include/node/v8.h:141:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../core.mm:96:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/leo/.node-gyp/8.6.0/include/node/v8.h:876:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../core.mm:100:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(Null());
               ~~~~~ ^
../core.mm:100:28: error: no matching function for call to 'Null'
        return scope.Close(Null());
                           ^~~~
/Users/leo/.node-gyp/8.6.0/include/node/v8.h:313:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Local<Primitive> Null(Isolate* isolate);
                          ^
../core.mm:103:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(Null());
               ~~~~~ ^
../core.mm:103:28: error: no matching function for call to 'Null'
        return scope.Close(Null());
                           ^~~~
/Users/leo/.node-gyp/8.6.0/include/node/v8.h:313:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Local<Primitive> Null(Isolate* isolate);
                          ^
../core.mm:105:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an rvalue of type 'int'
        Local<Array> arr(Array::New(2));
                                    ^
/Users/leo/.node-gyp/8.6.0/include/node/v8.h:3465:36: note: passing argument to parameter 'isolate' here
  static Local<Array> New(Isolate* isolate, int length = 0);
                                   ^
../core.mm:106:36: error: too few arguments to function call, expected 2, have 1
        arr->Set(0, Number::New(log));
                    ~~~~~~~~~~~    ^
/Users/leo/.node-gyp/8.6.0/include/node/v8.h:2857:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../core.mm:107:36: error: too few arguments to function call, expected 2, have 1
        arr->Set(1, Number::New(lat));
                    ~~~~~~~~~~~    ^
/Users/leo/.node-gyp/8.6.0/include/node/v8.h:2857:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../core.mm:108:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(arr);
               ~~~~~ ^
../core.mm:114:31: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)' (aka
      'v8::Local<v8::Value> (const v8::internal::Arguments &)')
        FunctionTemplate::New(GetLocation)->GetFunction());
                              ^~~~~~~~~~~
/Users/leo/.node-gyp/8.6.0/include/node/v8.h:5351:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
../core.mm:113:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("getLocation"),
                ~~~~~~~~^
1 warning and 12 errors generated.
make: *** [Release/obj.target/node_corelocation/core.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.6.0/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/leo/GoogleDrive/src/node-corelocation
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by tmcw** [comment]
This module is up for adoption: I don't actively develop or support it. It looks like, from this error message, that the version of V8 it targeted originally is now far behind Node's, and it would need an update to the new V8 APIs.

**Comment by tmcw** [comment]
👍 @0i0 can you delete your fork of this repository so that I can transfer it to you?

**Comment by 0i0** [comment]
fork deleted

**Comment by tmcw** [comment]
Awesome, thanks for adopting this project!

**Comment by 0i0** [comment]
no more errors for the time being
